import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    translation: {
      dashboard: "Dashboard", overview: "Overview", cropPlanner: "Crop Planner", scanCrop: "Scan Crop", riskSimulator: "Risk Simulator", yieldEstimator: "Yield Estimator", smartInsights: "Smart Insights", healthReport: "Health Report", profitReports: "Profit Reports", diseaseAlerts: "Disease Alerts", help: "Help", logout: "Logout", goodMorning: "Good morning", goodAfternoon: "Good afternoon", goodEvening: "Good evening", newAnalysis: "New Analysis", topCrop: "Top Crop", riskLevel: "Risk Level", diseaseAlert: "Disease Alert", estimatedYieldLoss: "Est. Yield Loss", confidence: "Confidence", roi: "ROI", severity: "Severity", soilType: "Soil Type", farmSize: "Farm", riskOverview: "Risk Overview", rainfallDeviation: "Rainfall Deviation", temperature: "Temperature", marketTrend: "Market Trend", pestPressure: "Pest Pressure", optimal: "Optimal", neutral: "Neutral", low: "Low", medium: "Medium", high: "High", nitrogen: "Nitrogen (N)", phosphorous: "Phosphorous (P)", potassium: "Potassium (K)", ph: "pH Level", humidity: "Humidity (%)", rainfall: "Rainfall (mm)", season: "Season", farmSizeInput: "Farm Size", soilTypeInput: "Soil Type", irrigationInput: "Irrigation", previousCrop: "Previous Crop", analyzeCrop: "Analyze Crop", recommendations: "Recommendations", topRecommendation: "Top Recommendation", alternatives: "Alternatives", sowingWindow: "Sowing Window", fertilizerPlan: "Fertilizer Plan", seedVarieties: "Seed Varieties", croppingAdvice: "Cropping Rotation", marketAnalysis: "Market Analysis", uploadImage: "Upload Image", selectFromCamera: "Scan with Camera", selectCrop: "Select Crop", analyzeCropImage: "Analyze", disease: "Disease", treatment: "Treatment", yieldloss: "Yield Loss", estimatedProfit: "Est. Profit", revenue: "Revenue", cost: "Cost", netProfit: "Net Profit", perAcre: "per Acre", weatherUnavailable: "Weather unavailable", location: "Location", wind: "Wind", pressure: "Pressure", loading: "Loading...", 
        noRecommendations: "No recommendations available", 
        whatShouldIDo: "What Should I Do Today?", 
        todaysRecommendations: "Today's Recommendations",
        currentConditions: "Current Conditions",
        // advisory titles (backend + local)
        irrigationSuggested: "Irrigation Suggested",
        pestMonitoring: "Pest Monitoring",
        avoidFertilizer: "Avoid Fertilizer",
        fertilizerWindow: "Fertilizer Window",
        cropPlanningTitle: "Crop Planning",
        diseaseTreatmentTitle: "Disease Treatment",
        equipmentCheckTitle: "Equipment & Irrigation Check",
        highRiskActionsTitle: "High Risk Actions",
        localCropRecommendationTitle: "Crop Recommendation",
        localDiseaseManagementTitle: "Disease Management",
        generalMonitoringTitle: "General Monitoring",
        yieldPlanningTitle: "Yield Planning",
        diseaseCheckTitle: "Disease Check",
        // advisory messages (backend + local)
        highTempIrrigation: "High temperature detected. Light irrigation recommended today.",
        highHumidityPests: "High humidity increases pest risk. Inspect crops today.",
        rainAvoidFert: "Rain expected. Do not apply fertilizers today.",
        fertWindowMsg: "Good time to apply nitrogen fertilizer in next 2–3 days.",
        cropPlanningMessage: "Consider planting {{crop}} based on your recent soil analysis.",
        diseaseTreatmentMessage: "{{diseaseName}} detected with {{severity}}% severity. Apply treatment immediately.",
        equipmentCheckMessage: "Large farm detected. Check irrigation equipment today.",
        highRiskActionsMessage: "Conditions look risky today. Prioritize crop monitoring and avoid major input costs.",
        localCropRecommendationMessage: "Based on your latest analysis, {{crop}} is a strong option to focus on today.",
        localDiseaseManagementMessage: "{{diseaseName}} detected with {{severity}}%. Inspect fields and apply recommended treatment today.",
        generalMonitoringMessage: "No specific alerts for today. Walk your fields, check soil moisture, and record observations.",
        yieldPlanningMessage: "Projected yield is {{expectedYield}}. Plan input use and market options accordingly today.",
        diseaseCheckMessage: "Recent disease scan for {{diseaseName}} looks manageable. Continue regular scouting today.",
        cancel: "Cancel", save: "Save", submit: "Submit", language: "Language"
    }
  },
  hi: {
    translation: {
      dashboard: "डैशबोर्ड", overview: "अवलोकन", cropPlanner: "फसल योजना", scanCrop: "फसल स्कैन करें", riskSimulator: "जोखिम सिमुलेटर", yieldEstimator: "उपज अनुमानक", smartInsights: "स्मार्ट अंतर्दृष्टि", healthReport: "स्वास्थ्य रिपोर्ट", profitReports: "मुनाफा रिपोर्ट", diseaseAlerts: "रोग सतर्कताएं", help: "मदद", logout: "लॉगआउट", goodMorning: "शुभ प्रभात", goodAfternoon: "शुभ अपराह्न", goodEvening: "शुभ संध्या", newAnalysis: "नया विश्लेषण", topCrop: "शीर्ष फसल", riskLevel: "जोखिम स्तर", diseaseAlert: "रोग सतर्कता", estimatedYieldLoss: "अनुमानित उपज हानि", confidence: "आत्मविश्वास", roi: "निवेश पर रिटर्न", severity: "गंभीरता", soilType: "मिट्टी का प्रकार", farmSize: "खेत", riskOverview: "जोखिम अवलोकन", rainfallDeviation: "वर्षा विचलन", temperature: "तापमान", marketTrend: "बाजार प्रवृत्ति", pestPressure: "कीट दबाव", optimal: "इष्ट", neutral: "तटस्थ", low: "कम", medium: "मध्यम", high: "उच्च", nitrogen: "नाइट्रोजन (N)", phosphorous: "फॉस्फोरस (P)", potassium: "पोटेशियम (K)", ph: "pH स्तर", humidity: "आर्द्रता (%)", rainfall: "वर्षा (मिमी)", season: "मौसम", farmSizeInput: "खेत का आकार", soilTypeInput: "मिट्टी का प्रकार", irrigationInput: "सिंचाई", previousCrop: "पिछली फसल", analyzeCrop: "फसल का विश्लेषण करें", recommendations: "सिफारिशें", topRecommendation: "शीर्ष सिफारिश", alternatives: "विकल्प", sowingWindow: "बुवाई की खिड़की", fertilizerPlan: "उर्वरक योजना", seedVarieties: "बीज किस्में", croppingAdvice: "फसल रोटेशन", marketAnalysis: "बाजार विश्लेषण", uploadImage: "छवि अपलोड करें", selectFromCamera: "कैमरे से स्कैन करें", selectCrop: "फसल का चयन करें", analyzeCropImage: "विश्लेषण करें", disease: "रोग", treatment: "उपचार", yieldloss: "उपज हानि", estimatedProfit: "अनुमानित लाभ", revenue: "राजस्व", cost: "लागत", netProfit: "शुद्ध लाभ", perAcre: "प्रति एकड़", weatherUnavailable: "मौसम अनुपलब्ध", location: "स्थान", wind: "हवा", pressure: "दबाव", loading: "लोड हो रहा है...", error: "त्रुटि", success: "सफलता", cancel: "रद्द करें", save: "सहेजें", submit: "जमा करें", language: "भाषा"
    }
  },
  mr: {
    translation: {
      dashboard: "डॅशबोर्ड", overview: "अवलोकन", cropPlanner: "पीक नियोजन", scanCrop: "पीक स्कॅन करा", riskSimulator: "जोखीम सिम्युलेटर", yieldEstimator: "उत्पादन अनुमानकर्ता", smartInsights: "स्मार्ट अंतर्दृष्टी", healthReport: "आरोग्य अहवाल", profitReports: "नफा अहवाल", diseaseAlerts: "रोग सतर्कता", help: "मदत", logout: "बाहेर पडा", goodMorning: "शुभ प्रभात", goodAfternoon: "शुभ दुपार", goodEvening: "शुभ संध्या", newAnalysis: "नवीन विश्लेषण", topCrop: "शीर्ष पीक", riskLevel: "जोखीम पातळी", diseaseAlert: "रोग सतर्कता", estimatedYieldLoss: "अनुमानित उत्पादन नुकसान", confidence: "आत्मविश्वास", roi: "गुंतवणुकीवर परतावा", severity: "तीव्रता", soilType: "मातीचा प्रकार", farmSize: "शेत", riskOverview: "जोखीम अवलोकन", rainfallDeviation: "पावसाचे विचलन", temperature: "तापमान", marketTrend: "बाजार प्रवृत्ती", pestPressure: "कीटक दबाव", optimal: "इष्ट", neutral: "तटस्थ", low: "कमी", medium: "मध्यम", high: "उच्च", nitrogen: "नायट्रोजन (N)", phosphorous: "फॉस्फोरस (P)", potassium: "पोटॅशियम (K)", ph: "pH पातळी", humidity: "आर्द्रता (%)", rainfall: "पाऊस (मिमी)", season: "ऋतू", farmSizeInput: "शेत आकार", soilTypeInput: "मातीचा प्रकार", irrigationInput: "सिंचन", previousCrop: "मागील पीक", analyzeCrop: "पीकचे विश्लेषण करा", recommendations: "सुझाव", topRecommendation: "शीर्ष सुझाव", alternatives: "पर्याय", sowingWindow: "बोवणीची खिडकी", fertilizerPlan: "खते योजना", seedVarieties: "बीज जाती", croppingAdvice: "पीक फिरवणी", marketAnalysis: "बाजार विश्लेषण", uploadImage: "प्रतिमा अपलोड करा", selectFromCamera: "कॅमेरापासून स्कॅन करा", selectCrop: "पीक निवडा", analyzeCropImage: "विश्लेषण करा", disease: "रोग", treatment: "उपचार", yieldloss: "उत्पादन नुकसान", estimatedProfit: "अनुमानित नफा", revenue: "महसूल", cost: "खर्च", netProfit: "निव्वळ नफा", perAcre: "प्रति एकर", weatherUnavailable: "हवामान उपलब्ध नाही", location: "स्थान", wind: "वारा", pressure: "दबाव", loading: "लोड होत आहे...", error: "त्रुटी", success: "यशस्वी", cancel: "रद्द करा", save: "जतन करा", submit: "सादर करा", language: "भाषा"
    }
  },
  ta: {
    translation: {
      dashboard: "டாஷ்போர்டு", overview: "பார்வை", cropPlanner: "பயிர் திட்டம்", scanCrop: "பயிர் ஸ்கேன் செய்க", riskSimulator: "ஆபத்து உருவகப்படுத்தி", yieldEstimator: "விளைச்சல் மதிப்பீட்டாளர்", smartInsights: "ஸ்மார்ட் நுண்ணறிவு", healthReport: "ஆரோக்கிய அறிக்கை", profitReports: "லாभ அறிக்கைகள்", diseaseAlerts: "நோய் எச்சரிக்கைகள்", help: "உதவி", logout: "வெளியேறு", goodMorning: "காலை வணக்கம்", goodAfternoon: "மாலை வணக்கம்", goodEvening: "மாலை வணக்கம்", newAnalysis: "புதிய பகுப்பாய்வு", topCrop: "சிறந்த பயிர்", riskLevel: "ஆபத்து நிலை", diseaseAlert: "நோய் எச்சரிக்கை", estimatedYieldLoss: "மதிப்பிடப்பட்ட விளைச்சல் இழப்பு", confidence: "நம்பிக்கை", roi: "முதலீட்டு வருவாய்", severity: "கடுமை", soilType: "மண் வகை", farmSize: "பண்ணை", riskOverview: "ஆபத்து பார்வை", rainfallDeviation: "மழை விலகம்", temperature: "வெப்பநிலை", marketTrend: "சந்தை போக்கு", pestPressure: "பூச்சி அழுத்தம்", optimal: "உகந்த", neutral: "நடுநிலை", low: "குறைந்த", medium: "நடுத்தர", high: "உயர்", nitrogen: "நைட்ரஜன் (N)", phosphorous: "பாஸ்பரஸ் (P)", potassium: "பொட்டாசியம் (K)", ph: "pH நிலை", humidity: "ஈரப்பதம் (%)", rainfall: "மழைப்பொழிவு (மிமீ)", season: "பருவம்", farmSizeInput: "பண்ணை அளவு", soilTypeInput: "மண் வகை", irrigationInput: "நீர்ப்பாசனம்", previousCrop: "முந்தைய பயிர்", analyzeCrop: "பயிர் விश்லேષணம்", recommendations: "பரிந்துரைகள்", topRecommendation: "சிறந்த பரிந்துரை", alternatives: "மாற்றுகள்", sowingWindow: "விதை வாரியம்", fertilizerPlan: "உர திட்டம்", seedVarieties: "விதை வகைகள்", croppingAdvice: "பயிர் சுழற்சி", marketAnalysis: "சந்தை பகுப்பாய்வு", uploadImage: "படம் பதிவிறக்க", selectFromCamera: "கேமரா பதிவிறக்க", selectCrop: "பயிர் தேர்ந்தெடுக்கவும்", analyzeCropImage: "பகுப்பாய்வு செய்க", disease: "நோய்", treatment: "சிகிச்சை", yieldloss: "விளைச்சல் இழப்பு", estimatedProfit: "மதிப்பிடப்பட்ட லाभ", revenue: "வருவாய்", cost: "செலவு", netProfit: "நிகர லाभ", perAcre: "ஒரு ஏக்கருக்கு", weatherUnavailable: "வானிலை கிடைக்கவில்லை", location: "இடம்", wind: "காற்று", pressure: "அழுத்தம்", loading: "ஏற்றுதல் நடந்து கொண்டுள்ளது...", error: "பிழை", success: "வெற்றி", cancel: "ரத்து", save: "சேமி", submit: "சமர்ப்பண", language: "மொழி"
    }
  },
  te: {
    translation: {
      dashboard: "డాష్‌బోర్డ్", overview: "అవలోకనం", cropPlanner: "పంట ప్రణాళిక", scanCrop: "పంత స్కైన్ చేయండి", riskSimulator: "ప్రమాద ఉపకరణం", yieldEstimator: "పంట అంచనా", smartInsights: "స్మార్ట్ అంతర్దృష్టి", healthReport: "ఆరోగ్య నివేదన", profitReports: "లాభ నివేదనలు", diseaseAlerts: "వ్యాధి అజ్ఞప్తులు", help: "సహాయం", logout: "లాగ్ అవుట్", goodMorning: "శుభోదయం", goodAfternoon: "శుభ మధ్యాహ్నం", goodEvening: "శుభ సంధ్య", newAnalysis: "కొత్త విశ्లేషణ", topCrop: "ఉన్నత పంత", riskLevel: "ప్రమాద స్థితి", diseaseAlert: "వ్యాధి జ్ఞప్తి", estimatedYieldLoss: "అంచనా పంత నష్టం", confidence: "విశ్వాసం", roi: "పెట్టుబడుల రిటర్న", severity: "తీవ్రత", soilType: "మట్టి రకం", farmSize: "సంస్థ", riskOverview: "ప్రమాద అవలోకనం", rainfallDeviation: "వర్షాల విచలనం", temperature: "ఉష్ణోగ్రత", marketTrend: "మార్కెట్ ట్రెండ్", pestPressure: "చీమల ఒత్తిడి", optimal: "సరైన", neutral: "తటస్థ", low: "తక్కువ", medium: "మధ్యమ", high: "ఎక్కువ", nitrogen: "నత్రజని (N)", phosphorous: "ఫాస్ఫరస్ (P)", potassium: "పొటాషియం (K)", ph: "pH స్థితి", humidity: "ఆర్ద్రత (%)", rainfall: "వర్షాలు (mm)", season: "ఋతువు", farmSizeInput: "సంస్థ పరిమాణం", soilTypeInput: "మట్టి రకం", irrigationInput: "నీటిపాలన", previousCrop: "మునుపటి పంత", analyzeCrop: "పంత విశ़్లేషణ", recommendations: "సిఫారసులు", topRecommendation: "ఉన్నత సిఫారసు", alternatives: "ప్రత్యామ్నాయాలు", sowingWindow: "విత్తన భవనం", fertilizerPlan: "సారి ప్రణాళిక", seedVarieties: "విత్తన రకాలు", croppingAdvice: "పంత భ్రమణ", marketAnalysis: "మార్కెట్ విశ்లేషణ", uploadImage: "చిత్రం అప్‌లోడ్ చేయండి", selectFromCamera: "కెమెరా నుండి స్కాన్ చేయండి", selectCrop: "పంతను ఎంచుకోండి", analyzeCropImage: "విశ్లేషణ చేయండి", disease: "వ్యాధి", treatment: "చికిత్స", yieldloss: "పంత నష్టం", estimatedProfit: "అంచనా లాభ", revenue: "రాజస్వం", cost: "ఖర్చు", netProfit: "నికర లాభ", perAcre: "ఎకరానికి", weatherUnavailable: "వాతావరణం అందుబాటులో లేదు", location: "స్థానం", wind: "గాలి", pressure: "ఒత్తిడి", loading: "లోడ్ చేస్తోంది...", error: "లోపం", success: "వాগ్దత", cancel: "రద్దు", save: "సేవ్ చేయండి", submit: "సమర్పించండి", language: "భాష"
    }
  },
  bn: {
    translation: {
      dashboard: "ড্যাশবোর্ড", overview: "সংক্ষিप্ত বিবরণ", cropPlanner: "ফসল পরিকল্পনা", scanCrop: "ফসল স্কেন করুন", riskSimulator: "ঝুঁকি সিমুলেটর", yieldEstimator: "ফলন অনুমানক", smartInsights: "স্মার্ট অন্তর্দৃষ্টি", healthReport: "স্বাস্থ্য প্রতিবেদন", profitReports: "লাভ প্রতিবেদন", diseaseAlerts: "রোগ সতর্কতা", help: "সাহায্য", logout: "লগআউট", goodMorning: "শুভ সকাল", goodAfternoon: "শুভ দুপুর", goodEvening: "শুভ সন্ধ্যা", newAnalysis: "নতুন বিশ্লেষণ", topCrop: "শীর্ষ ফসল", riskLevel: "ঝুঁকি স্তর", diseaseAlert: "রোগ সতর্কতা", estimatedYieldLoss: "অনুমানিত ফলন ক্ষতি", confidence: "আত্মবিশ্বাস", roi: "বিনিয়োগের রিটার্ন", severity: "গুরুত্বতা", soilType: "মাটির ধরন", farmSize: "খামার", riskOverview: "ঝুঁকি সংক्षिप্ত बिवरण", rainfallDeviation: "বৃষ্টিপাত বিচ্যুতি", temperature: "তাপমাত्रা", marketTrend: "বাজার প्রবণता", pestPressure: "कीट चाप", optimal: "सर्वোत्क़", neutral: "निरpेक्ष", low: "निम्न", medium: "मध्यम", high: "उच्च", nitrogen: "नाइট्रोजन (N)", phosphorous: "फॉस्फरस (P)", potassium: "पोटाशियम (K)", ph: "pH स्तर", humidity: "आर्द्रता (%)", rainfall: "वर्षा (मिमी)", season: "ऋतु", farmSizeInput: "खेत आकार", soilTypeInput: "मिट्टी प्रकार", irrigationInput: "सिंचाई", previousCrop: "पिछली फसल", analyzeCrop: "फसल विश्लेषण", recommendations: "सिफारिशें", topRecommendation: "शीर्ष सिफारिश", alternatives: "विकल्प", sowingWindow: "बुवाई खिड़की", fertilizerPlan: "उर्वरक योजना", seedVarieties: "बीज किस्में", croppingAdvice: "फसल रोटेशन", marketAnalysis: "बाजार विश्लेषण", uploadImage: "चित्र अपलोड", selectFromCamera: "कैमरे से स्कैन", selectCrop: "फसल चयन", analyzeCropImage: "विश्लेषण करें", disease: "रोग", treatment: "उपचार", yieldloss: "फलन नुकसान", estimatedProfit: "अनुमानित लाभ", revenue: "राजस्व", cost: "लागत", netProfit: "शुद्ध लाभ", perAcre: "प्रति एकड़", weatherUnavailable: "मौसम अनुपलब्ध", location: "स्थान", wind: "हवा", pressure: "दबाव", loading: "लोड हो रहा है...", error: "त्रुटि", success: "सफलता", cancel: "रद्द करें", save: "सहेजें", submit: "जमा करें", language: "भाषा"
    }
  },
  gu: {
    translation: {
      dashboard: "ડેશબોર્ડ", overview: "અવલોકન", cropPlanner: "પાકની યોજના", scanCrop: "પાક સ્કેન કરો", riskSimulator: "જોખમ સિમ્યુલેટર", yieldEstimator: "ઉપજ અંદાજેકાર", smartInsights: "સ્માર્ટ આંતર્દૃષ્ટિ", healthReport: "આરોગ્ય અહેવાલ", profitReports: "નફો અહેવાલો", diseaseAlerts: "રોગ ચેતવણીઓ", help: "મદદ", logout: "લૉગ આઉટ", goodMorning: "શુભ સવાર", goodAfternoon: "શુભ બપોર", goodEvening: "શુભ સાંજ", newAnalysis: "નવું વિશ્લેષણ", topCrop: "ટોપ પાક", riskLevel: "જોખમ સ્તર", diseaseAlert: "રોગ ચેતવણી", estimatedYieldLoss: "અનુમાનિત ઉપજ નુકશાન", confidence: "આત્મવિશ્વાસ", roi: "રોકાણ પરત", severity: "તીવ્રતા", soilType: "માટી પ્રકાર", farmSize: "ખેત", riskOverview: "જોખમ અવલોકન", rainfallDeviation: "વરસાદ વિચલન", temperature: "તાપમાન", marketTrend: "બજાર ટ્રેન્ડ", pestPressure: "જંતુ દબાણ", optimal: "શ્રેષ્ઠ", neutral: "તટસ્થ", low: "નીચું", medium: "મધ્યમ", high: "ઊંચું", nitrogen: "નાઇટ્રોજન (N)", phosphorous: "ફૉસ્ફોરસ (P)", potassium: "પોટેશિયમ (K)", ph: "pH સ્તર", humidity: "ભેજ (%)", rainfall: "વરસાદ (મીમી)", season: "ઋતુ", farmSizeInput: "ખેતનું કદ", soilTypeInput: "માટી પ્રકાર", irrigationInput: "સિંચાઈ", previousCrop: "પાછલો પાક", analyzeCrop: "પાક વિશ્લેષણ", recommendations: "સલાહો", topRecommendation: "ટોપ સલાહ", alternatives: "વિકલ્પો", sowingWindow: "વાવણીની વિંડો", fertilizerPlan: "ખાદ યોજના", seedVarieties: "બીજ જાતો", croppingAdvice: "પાક પરિભ્રમણ", marketAnalysis: "બજાર વિશ્લેષણ", uploadImage: "ચિત્ર અપલોડ કરો", selectFromCamera: "કેમેરા થી સ્કેન કરો", selectCrop: "પાક પસંદ કરો", analyzeCropImage: "વિશ્લેષણ કરો", disease: "રોગ", treatment: "સારવાર", yieldloss: "ઉપજ નુકશાન", estimatedProfit: "અનુમાનિત નફો", revenue: "આવક", cost: "ખર્ચ", netProfit: "નિવલ નફો", perAcre: "પ્રતિ એકર", weatherUnavailable: "આબોહવા ઉપલબ્ધ નથી", location: "સ્થાન", wind: "પવન", pressure: "દબાણ", loading: "લોડ થઈ રહ્યું છે...", error: "ભૂલ", success: "સફલતા", cancel: "રદ કરો", save: "સાચવો", submit: "સબમિટ કરો", language: "ભાષા"
    }
  },
  kn: {
    translation: {
      dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್", overview: "ನಿರೀಕ್ಷಣ", cropPlanner: "ಸಸ್ಯ ಯೋಜನೆ", scanCrop: "ಸಸ್ಯ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ", riskSimulator: "ಅಪಾಯ ಸಿಮ್ಯುಲೇಟರ್", yieldEstimator: "ಇಳುವರಿ ಅಂದಾಜುಕಾರ", smartInsights: "ಸ್ಮಾರ್ಟ್ ಒಳನೋಟಗಳು", healthReport: "ಸ್ವಾಸ್ಥ್ಯ ವರದಿ", profitReports: "ಲಾಭ ವರದಿಗಳು", diseaseAlerts: "ರೋಗ ಎಚ್ಚರಿಕೆಗಳು", help: "ಸಹಾಯ", logout: "ಲಾಗ್ ಔಟ್", goodMorning: "ಶುಭೋದಯ", goodAfternoon: "ಶುಭ ಮಧ್ಯಾಹ್ನ", goodEvening: "ಶುಭ ಸಂಧ್ಯೆ", newAnalysis: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ", topCrop: "ಉನ್ನತ ಸಸ್ಯ", riskLevel: "ಅಪಾಯ ಪ್ರಮಾಣ", diseaseAlert: "ರೋಗ ಎಚ್ಚರಿಕೆ", estimatedYieldLoss: "ಅಂದಾಜಿತ ಇಳುವರಿ ನಷ್ಟ", confidence: "ಆತ್ಮವಿಶ್ವಾಸ", roi: "ಹೂಡಿಕೆ ಖರೀದಿ", severity: "ಗಂಭೀರತೆ", soilType: "ಮಣ್ಣಿನ ಪ್ರಕಾರ", farmSize: "ತೋಟ", riskOverview: "ಅಪಾಯ ನಿರೀಕ್ಷಣ", rainfallDeviation: "ವರ್ಷಾಪಾತ ವಿಚಲನ", temperature: "ತಾಪಮಾನ", marketTrend: "ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿ", pestPressure: "ಕೀಟ ಒತ್ತಡ", optimal: "ಸರ್ವೋತ್ತಮ", neutral: "ತಟಸ್ಥ", low: "ನಿಮ್ನ", medium: "ಮಧ್ಯಮ", high: "ಉಚ್ಚ", nitrogen: "ಸೂಜಕೃತ್ಯ (N)", phosphorous: "ಫಾಸ್ಫರಸ್ (P)", potassium: "ಪೊಟ್ಯಾಸಿಯಮ್ (K)", ph: "pH ಪ್ರಮಾಣ", humidity: "ಆರ್ದ್ರತೆ (%)", rainfall: "ವರ್ಷಾಪಾತ (ಮಿ.ಮೀ)", season: "ಋತು", farmSizeInput: "ತೋಟ ಆಕಾರ", soilTypeInput: "ಮಣ್ಣಿನ ಪ್ರಕಾರ", irrigationInput: "ನೀರಾವರಿಕೆ", previousCrop: "ಹಿಂದಿನ ಸಸ್ಯ", analyzeCrop: "ಸಸ್ಯ ವಿಶ್ಲೇಷಣೆ", recommendations: "ಸಲಹೆಗಳು", topRecommendation: "ಉನ್ನತ ಸಲಹೆ", alternatives: "ಪರ್ಯಾಯಗಳು", sowingWindow: "ಸಿದ್ಧ ವಿಂಡೋ", fertilizerPlan: "ರಸಗೊಬ್ಬರ ಯೋಜನೆ", seedVarieties: "ಬೀಜ ಪ್ರಭೇದಗಳು", croppingAdvice: "ಸಸ್ಯ ಪರಿಭ್ರಮಣ", marketAnalysis: "ಮಾರುಕಟ್ಟೆ ವಿಶ್ಲೇಷಣೆ", uploadImage: "ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ", selectFromCamera: "ಕ್ಯಾಮರಾದಿಂದ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ", selectCrop: "ಸಸ್ಯ ಆರಿಸಿ", analyzeCropImage: "ವಿಶ್ಲೇಷಣೆ ಮಾಡಿ", disease: "ರೋಗ", treatment: "ಚಿಕಿತ್ಸೆ", yieldloss: "ಇಳುವರಿ ನಷ್ಟ", estimatedProfit: "ಅಂದಾಜಿತ ಲಾಭ", revenue: "ಆದಾಯ", cost: "ವೆಚ್ಚ", netProfit: "ನಿವ್ವಳ ಲಾಭ", perAcre: "ಪ್ರತಿ ಎಕರೆ", weatherUnavailable: "ಹವಾಮಾನ ಲಭ್ಯವಿಲ್ಲ", location: "ಸ್ಥಳ", wind: "ಗಾಳಿ", pressure: "ಒತ್ತಡ", loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...", error: "ದೋಷ", success: "ಯಶಸ್ಸು", cancel: "ರದ್ದುಗೊಳಿಸಿ", save: "ಸಂರಕ್ಷಿಸಿ", submit: "ಸಮರ್ಪಿಸಿ", language: "ಭಾಷೆ"
    }
  },
  pa: {
    translation: {
      dashboard: "ਡੈਸ਼ਬੋਰਡ", overview: "ਜਾਣਕਾਰੀ", cropPlanner: "ਫਸਲ ਯੋਜਨਾ", scanCrop: "ਫਸਲ ਸਕੈਨ ਕਰੋ", riskSimulator: "ਜੋਖਮ ਸਿਮੂลೇਟਰ", yieldEstimator: "ਪੈਦਾਵਾਰ ਅਨੁਮਾਨ", smartInsights: "ਸਮਾਰਟ ਅੰਤਰਦ੍ਰਿਸ਼ਟੀ", healthReport: "ਸਿਹਤ ਰਿਪੋਰਟ", profitReports: "ਲਾਭ ਰਿਪੋਰਟ", diseaseAlerts: "ਰੋਗ ਸਚੇتਨਾ", help: "ਸਹਾਇਤਾ", logout: "ਲਾਗ ਆਉਟ", goodMorning: "ਸ਼ੁਭ ਸਵੇਰ", goodAfternoon: "ਸ਼ੁਭ ਦੁਪਹਿਰ", goodEvening: "ਸ਼ੁਭ ਸ਼ਾਮ", newAnalysis: "ਨਵਾਂ ਵਿਸ਼ਲੇਸ਼ਣ", topCrop: "ਸ਼ੀਰਸ਼ ਫਸਲ", riskLevel: "ਜੋਖਮ ਪੱਧਰ", diseaseAlert: "ਰੋਗ ਸਚੇतਨਾ", estimatedYieldLoss: "ਅਨੁਮਾਨਿਤ ਪੈਦਾਵਾਰ ਨੁਕਸਾਨ", confidence: "ਆਤਮਵਿਸ਼ਵਾਸ", roi: "ਨਿਵੇਸ਼ ਤੇ ਵਾਪਸੀ", severity: "ਗੰਭੀrता", soilType: "गिट्टੀ ਦੀ ਕਿਸਮ", farmSize: "ਖੇत", riskOverview: "ਜੋਖਮ ਜਾਣਕਾਰੀ", rainfallDeviation: "ਬਾਰੀsh ਖਿԲੀਧੀ", temperature: "ਤਾпीมਾਨ", marketTrend: "ਮার्किﻞ ਰुझਾਨ", pestPressure: "कीટ ਦbاء", optimal: "ਸрવોत्तम", neutral: "तटस्थ", low: "घט्ቅ", medium: "म्ধिम", high: "उच्च", nitrogen: "नाइট्रोजन (N)", phosphorous: "फॉस्फोरस (P)", potassium: "पोटेशियम (K)", ph: "pH स्तर", humidity: "नमी (%)", rainfall: "mi mीँह (मि.मीं)", season: "मौसम", farmSizeInput: "खेत का आकार", soilTypeInput: "मिट्टी का प्रकार", irrigationInput: "सिंचाई", previousCrop: "पिछली फसल", analyzeCrop: "फसल का विश्लेषण", recommendations: "सिफारिशें", topRecommendation: "शीर्ष सिफारिश", alternatives: "विकल्प", sowingWindow: "बुवाई की खिड़की", fertilizerPlan: "उर्वरक योजना", seedVarieties: "बीज किस्में", croppingAdvice: "फसल रोटेशन", marketAnalysis: "बाजार विश्लेषण", uploadImage: "छवि अपलोड करें", selectFromCamera: "कैमरे से स्कैन करें", selectCrop: "फसल का चयन", analyzeCropImage: "विश्लेषण करें", disease: "रोग", treatment: "उपचार", yieldloss: "पैदावार नुकसान", estimatedProfit: "अनुमानित लाभ", revenue: "राजस्व", cost: "लागत", netProfit: "शुद्ध लाभ", perAcre: "प्रति एकड़", weatherUnavailable: "मौसम अनुपलब्ध", location: "स्थान", wind: "हवा", pressure: "दबाव", loading: "लोड हो रहा है...", error: "त्रुटि", success: "सफलता", cancel: "रद्द करें", save: "सहेजें", submit: "जमा करें", language: "भाषा"
    }
  },
  ml: {
    translation: {
      dashboard: "ഡാഷ്ബോർഡ്", overview: "അവലോകനം", cropPlanner: "കൃഷി ആസൂത്രണം", scanCrop: "വിള സ്കാൻ ചെയ്യുക", riskSimulator: "അപകടം സിമുലേറ്റർ", yieldEstimator: "വിളവ് അനുമാനകൻ", smartInsights: "സ്മാർട്ട് അന്തർദൃഷ്ടി", healthReport: "ആരോഗ്യ റിപ്പോർട്ട്", profitReports: "ലാഭ റിപ്പോർട്ടുകൾ", diseaseAlerts: "രോഗ മുന്നറിപ്പുകൾ", help: "സഹായം", logout: "ലോഗ് ഔട്ട്", goodMorning: "ശുഭോദയം", goodAfternoon: "ശുഭ ദിനം", goodEvening: "ശുഭ സന്ധ്യ", newAnalysis: "പുതിയ വിശകലനം", topCrop: "എലിവേറ്റ് വിള", riskLevel: "അപകട നിലവാരം", diseaseAlert: "രോഗ മുന്നറിപ്പ്", estimatedYieldLoss: "കണക്കാക്കിയ വിളവ് നഷ്ടം", confidence: "ആത്മവിശ്വാസം", roi: "നിക്ഷേപത്തിൻ്റെ വരുമാനം", severity: "ഗുരുത്വം", soilType: "മണ്ണ് തരം", farmSize: "കൃഷിയിടം", riskOverview: "അപകട അവലോകനം", rainfallDeviation: "മഴ വ്യതിയാനം", temperature: "താപനില", marketTrend: "വിപണന പ്രവണത", pestPressure: "കീടങ്ങൾ സമ്മർദ്ദം", optimal: "അനുകൂലം", neutral: "നിരപേക്ഷ", low: "താഴ്ന്ന", medium: "മധ്യം", high: "ഉയർന്ന", nitrogen: "നൈട്രജൻ (N)", phosphorous: "ഫോസ്ഫറസ് (P)", potassium: "പൊട്ടാസ്യം (K)", ph: "pH നിലവാരം", humidity: "ആർദ്രത (%)", rainfall: "മഴ (മിമി)", season: "കാലം", farmSizeInput: "കൃഷിയിടത്തിൻ്റെ വലുപ്പം", soilTypeInput: "മണ്ണ് തരം", irrigationInput: "അരിച്ചെഞ്ച്", previousCrop: "മുൻ വിള", analyzeCrop: "വിള വിശകലനം", recommendations: "ശുപാർശകൾ", topRecommendation: "എലിവേറ്റ് ശുപാർശ", alternatives: "അകൽപ്പുകൾ", sowingWindow: "വിതറാൻ ജനാലകൾ", fertilizerPlan: "പച്ചിലം പദ്ധതി", seedVarieties: "വിത്ത് ഇനങ്ങൾ", croppingAdvice: "വിള പരിക്രമണം", marketAnalysis: "വിപണന വിശകലനം", uploadImage: "ചിത്രം അപ്ലോഡ് ചെയ്യുക", selectFromCamera: "ക്യാമെരയിൽ നിന്ന് സ്കാൻ ചെയ്യുക", selectCrop: "വിള തിരഞ്ഞെടുക്കുക", analyzeCropImage: "വിശകലനം ചെയ്യുക", disease: "രോഗം", treatment: "ചികിത്സ", yieldloss: "വിളവ് നഷ്ടം", estimatedProfit: "കണക്കാക്കിയ ലാഭം", revenue: "വരുമാനം", cost: "ചെലവ്", netProfit: "നെറ്റ് ലാഭം", perAcre: "ഒരു ഏക്കറിന്", weatherUnavailable: "കാലാവസ്ഥ ലഭ്യമല്ല", location: "സ്ഥാനം", wind: "കാറ്റ്", pressure: "സമ്മർദ്ദം", loading: "ലോഡ് ചെയ്യുന്നു...", error: "പിശക്", success: "വിജയം", cancel: "റദ്ദാക്കുക", save: "സംരക്ഷിക്കുക", submit: "സമർപ്പിക്കുക", language: "ഭാഷ"
    }
  }
};

i18n
.use(initReactI18next)
.init({
  resources,
  lng: localStorage.getItem("language") || "en",
  fallbackLng: "en",
  interpolation: {
    escapeValue: false
  }
});

export default i18n;