import { useAppStore } from '../store/useAppStore'
import { FileText, Download, CheckCircle, AlertTriangle } from 'lucide-react'

export default function ReportPage() {
  const { user, onboarding, cropRecommendation, diseaseResult } = useAppStore()

  const today = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })
  const rec = cropRecommendation?.recommendations?.[0]
  const d   = diseaseResult

  const handleDownload = () => {
    const content = `
KrishiShield Crop Health Report
================================
Generated: ${today}
Farmer: ${user?.username || 'Farmer'}
Location: ${user?.state || 'Maharashtra'}
Soil Type: ${onboarding?.landType || 'Loamy'} | pH 6.5
Season: Kharif 2025

CROP RECOMMENDATION
-------------------
Top Crop: ${rec?.name || 'Maize'}
Confidence: ${rec?.confidence || 87}%
Risk Level: ${rec?.risk || 'Medium'}
ROI Estimate: ${rec?.roi || '₹28,000–₹35,000'}/acre

DISEASE ANALYSIS
----------------
Disease: ${d?.name || 'Leaf Blight'}
Confidence: ${d?.confidence || 91}%
Severity: ${d?.level || 'Moderate'} (${d?.severity || 22}%)
Yield Loss: ${d?.yieldLoss || '14–18%'}
Financial Impact: ${d?.financialImpact || '₹4,200'}

TREATMENT
---------
${d?.treatments?.map(t => `• ${t.name} — ${t.dose} (${t.urgency} urgency, ${t.recovery}% recovery)`).join('\n') || '• Mancozeb 75% WP — 2g/litre water'}

YIELD ANALYSIS
--------------
Expected Yield: 55 q/acre
Estimated Loss: 14.2%
Financial Impact: -₹14,245
Net Revenue: ₹87,505

SUGGESTED ACTIONS
-----------------
• Immediate: Apply fungicide treatment
• Within 7 days: Nitrogen top-up (+5%)
• This month: Adjust irrigation schedule
• Harvest Window: March 18–25

Generated by KrishiShield — AI-Powered Crop Intelligence
    `.trim()

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url; a.download = `KrishiShield_Report_${today.replace(/\s/g,'_')}.txt`
    a.click(); URL.revokeObjectURL(url)
  }

  const Section = ({ title, rows }) => (
    <div className="card">
      <h3 className="font-semibold text-forest-800 mb-4 pb-3 border-b border-forest-100">{title}</h3>
      <div className="space-y-2">
        {rows.map(([k, v, style]) => (
          <div key={k} className="flex justify-between items-center py-2 border-b border-forest-50 last:border-0 text-sm">
            <span className="text-forest-500">{k}</span>
            <span className={`font-semibold ${style || 'text-forest-800'}`}>{v}</span>
          </div>
        ))}
      </div>
    </div>
  )

  return (
    <div className="space-y-6 animate-fade-in max-w-4xl">
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div>
          <h1 className="font-display text-2xl font-bold text-forest-800 flex items-center gap-2">
            <FileText className="text-forest-500" /> Crop Health Report
          </h1>
          <p className="text-forest-500 text-sm mt-1">Auto-generated comprehensive report — ready to download</p>
        </div>
        <button onClick={handleDownload}
          className="btn-primary flex items-center gap-2 text-sm">
          <Download size={16} /> Download Report
        </button>
      </div>

      {/* Header card */}
      <div className="bg-gradient-to-br from-forest-800 to-forest-600 rounded-2xl p-6 text-white">
        <div className="flex items-center gap-3 mb-5">
          <span className="text-3xl">🌾</span>
          <div>
            <div className="font-display font-bold text-xl">KrishiShield Crop Health Report</div>
            <div className="text-forest-300 text-sm">AI-Powered Agricultural Intelligence</div>
          </div>
        </div>
        <div className="grid sm:grid-cols-2 gap-3">
          {[
            ['Farmer',       user?.username || 'Farmer'],
            ['Location',     user?.state || 'Maharashtra'],
            ['Soil Type',    (onboarding?.landType || 'Loamy') + ' · pH 6.5'],
            ['Report Date',  today],
            ['Season',       'Kharif 2025'],
            ['Farm Size',    onboarding?.farmSize || '5–20 Acres'],
          ].map(([k, v]) => (
            <div key={k} className="bg-white/10 backdrop-blur-sm rounded-xl px-4 py-2.5 flex justify-between items-center">
              <span className="text-forest-200 text-xs">{k}</span>
              <span className="text-white font-semibold text-sm">{v}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Report sections */}
      <div className="grid md:grid-cols-2 gap-5">
        <Section title="🌱 Crop Recommendation" rows={[
          ['Top Crop',      rec?.name || 'Maize',                                      'text-forest-700'],
          ['Confidence',    `${rec?.confidence || 87}%`,                               'text-forest-700'],
          ['Risk Level',    rec?.risk?.charAt(0).toUpperCase() + (rec?.risk?.slice(1) || 'medium'), rec?.risk === 'high' ? 'text-red-600' : rec?.risk === 'low' ? 'text-forest-600' : 'text-earth-600'],
          ['ROI Estimate',  rec?.roi || '₹28,000–₹35,000',                            'text-forest-700'],
          ['Insight',       cropRecommendation?.rainfallDeviation ? `Rainfall: ${cropRecommendation.rainfallDeviation}` : 'Normal conditions', 'text-forest-500'],
        ]} />

        <Section title="🦠 Disease Analysis" rows={[
          ['Disease',       d?.name || 'Leaf Blight',                                  'text-red-600'],
          ['Confidence',    `${d?.confidence || 91}%`,                                 'text-forest-700'],
          ['Severity',      `${d?.level?.charAt(0).toUpperCase() + (d?.level?.slice(1) || 'Moderate')} (${d?.severity || 22}%)`, d?.level === 'severe' ? 'text-red-600' : 'text-earth-600'],
          ['Yield Loss',    d?.yieldLoss || '14–18%',                                  'text-red-600'],
          ['Financial Impact', d?.financialImpact || '₹4,200',                         'text-red-600'],
        ]} />

        <Section title="📉 Yield Analysis" rows={[
          ['Expected Yield',   '55 q/acre',  'text-forest-700'],
          ['Estimated Loss',   '14.2%',      'text-red-600'],
          ['Financial Impact', '-₹14,245',   'text-red-600'],
          ['Net Revenue',      '₹87,505',    'text-forest-700'],
          ['Crop Sensitivity', 'Medium',     'text-earth-600'],
        ]} />

        <Section title="⚡ Suggested Actions" rows={[
          ['Immediate',        'Apply fungicide treatment',   'text-red-600'],
          ['Within 7 days',    'Nitrogen top-up (+5%)',       'text-earth-600'],
          ['This month',       'Adjust irrigation schedule',  'text-forest-600'],
          ['Harvest Window',   'March 18–25, 2025',           'text-forest-700'],
          ['Next Season',      'Consider Rabi Wheat',         'text-forest-500'],
        ]} />
      </div>

      {/* Treatment detail */}
      {d?.treatments && (
        <div className="card">
          <h3 className="font-semibold text-forest-800 mb-4">💊 Detailed Treatment Plan</h3>
          <div className="space-y-3">
            {d.treatments.map((t, i) => (
              <div key={i} className="flex items-start gap-4 bg-forest-50 rounded-xl p-4 border border-forest-100">
                <div className="w-8 h-8 bg-forest-500 rounded-full text-white text-sm font-bold flex items-center justify-center shrink-0">
                  {i + 1}
                </div>
                <div className="flex-1">
                  <div className="flex items-start justify-between gap-2 flex-wrap">
                    <div className="font-semibold text-forest-800 text-sm">{t.name}</div>
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${t.urgency === 'Critical' || t.urgency === 'High' ? 'bg-red-100 text-red-700' : 'bg-earth-100 text-earth-700'}`}>
                      {t.urgency} Urgency
                    </span>
                  </div>
                  <div className="text-forest-500 text-xs mt-1 mb-2">Dose: {t.dose}</div>
                  <div className="flex items-center gap-2">
                    <div className="flex-1 h-1.5 bg-forest-200 rounded-full overflow-hidden">
                      <div className="h-full bg-forest-500 rounded-full" style={{ width: `${t.recovery}%` }} />
                    </div>
                    <span className="text-xs text-forest-500 font-medium">{t.recovery}% est. recovery</span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Download CTA */}
      <div className="bg-gradient-to-r from-forest-600 to-forest-500 rounded-2xl p-6 flex items-center justify-between flex-wrap gap-4">
        <div>
          <div className="font-display font-bold text-white text-lg">Download Full Report</div>
          <div className="text-forest-200 text-sm">Complete analysis with all findings and recommendations</div>
        </div>
        <button onClick={handleDownload}
          className="bg-white text-forest-700 hover:bg-forest-50 font-bold py-3 px-6 rounded-xl flex items-center gap-2 transition-all text-sm shadow-md hover:shadow-lg">
          <Download size={16} /> Download Report (.txt)
        </button>
      </div>
    </div>
  )
}
